title: ICS4U Blog | AYJ
author: Andrew R.
email: arusu1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  This is my blog for my computer science class at AYJ.
  It'll be going on my portfolio that I made for all my works done in this class.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
